/**
 * Taskito — Shared type definitions.
 * Single source of truth for all entity types, enums, and DTOs.
 * Every tRPC router input/output and component prop references these types.
 */

// ─── Enums ───────────────────────────────────────────────

/** Category grouping for workflow statuses */
export type StatusCategory = "backlog" | "todo" | "active" | "done" | "cancelled";

/** Types of directed links between tasks */
export type LinkType = "blocks" | "relates" | "parent" | "child";

/** Priority levels for tasks */
export type Priority = "none" | "low" | "medium" | "high" | "urgent";

/** Global application roles */
export type UserRole = "admin" | "member";

/** Project-scoped roles */
export type ProjectMemberRole = "owner" | "member";

/** Custom field types */
export type CustomFieldType = "text" | "number" | "date" | "select";

/** Time resolution for graph view */
export type TimeResolution = "day" | "week" | "month" | "quarter" | "year";

// ─── Entity interfaces ──────────────────────────────────

/** Top-level project container */
export interface Project {
  id: string;
  name: string;
  key: string;
  slug: string;
  description: string | null;
  settings: ProjectSettings;
  createdAt: Date;
  updatedAt: Date;
}

/** Membership linking a user to a project */
export interface ProjectMember {
  projectId: string;
  userId: string;
  role: ProjectMemberRole;
  createdAt: Date;
  updatedAt: Date;
}

/** JSON settings stored per project */
export interface ProjectSettings {
  defaultStatusId?: string;
  timeResolution?: TimeResolution;
  autoTagEnabled?: boolean;
}

/** User-defined workflow status within a project */
export interface WorkflowStatus {
  id: string;
  projectId: string;
  name: string;
  color: string;
  order: number;
  category: StatusCategory;
}

/** Allowed state transition between two statuses */
export interface WorkflowTransition {
  id: string;
  projectId: string;
  fromStatusId: string;
  toStatusId: string;
}

/** Core task entity */
export interface Task {
  id: string;
  projectId: string;
  title: string;
  description: unknown | null; // TipTap JSON
  statusId: string;
  priority: Priority;
  dueDate: Date;
  startDate: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

/** Task with relations loaded */
export interface TaskWithRelations extends Task {
  status: WorkflowStatus;
  tags: Tag[];
  links: TaskLink[];
  comments: Comment[];
  customFieldValues: CustomFieldValue[];
}

/** Directed edge between two tasks */
export interface TaskLink {
  id: string;
  sourceTaskId: string;
  targetTaskId: string;
  linkType: LinkType;
}

/** Project-scoped tag */
export interface Tag {
  id: string;
  projectId: string;
  name: string;
  color: string;
  isAutoGenerated: boolean;
}

/** Many-to-many join: task ↔ tag */
export interface TaskTag {
  taskId: string;
  tagId: string;
}

/** Comment on a task */
export interface Comment {
  id: string;
  taskId: string;
  authorId: string;
  content: string;
  createdAt: Date;
  attachments?: CommentAttachment[];
}

export interface CommentAttachment {
  id: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  createdAt: Date;
}

/** User-defined custom field per project */
export interface CustomField {
  id: string;
  projectId: string;
  name: string;
  type: CustomFieldType;
  options: Record<string, unknown> | null;
}

/** Value of a custom field for a specific task */
export interface CustomFieldValue {
  id: string;
  taskId: string;
  customFieldId: string;
  value: unknown;
}

/** Application user */
export interface User {
  id: string;
  name: string | null;
  email: string;
  image: string | null;
  role: UserRole;
}

/** Minimal user payload used in task assignment and attribution UI */
export interface TaskPersonSummary {
  id: string;
  name: string | null;
  email: string;
  image?: string | null;
}

/** Project fields commonly embedded on task payloads */
export interface ProjectReference {
  key: string;
  slug?: string;
}

/** Minimal project payload used by the project switcher */
export type ProjectSwitcherOption = Pick<Project, "id" | "name" | "slug" | "key">;

/** Minimal status shape used by board/list/task card views */
export interface TaskStatusSummary {
  id: string;
  name: string;
  color: string;
  category?: StatusCategory;
}

/** Minimal tag relation shape used by task cards */
export interface TaskTagSummary {
  tag: Pick<Tag, "id" | "name" | "color">;
}

/** Task payload shape used by board/list/task card views */
export interface TaskCardData {
  id: string;
  taskNumber?: number;
  title: string;
  priority: Priority;
  dueDate: Date | string;
  statusId: string;
  status: TaskStatusSummary;
  tags: TaskTagSummary[];
  creator?: TaskPersonSummary | null;
  assignee?: TaskPersonSummary | null;
  project?: ProjectReference;
  alertAcknowledged?: boolean;
  dependencyState?: {
    blockingTaskCount: number;
    openChildCount: number;
  };
}

/** Status payload used by board/task detail controls */
export type BoardStatus = Pick<WorkflowStatus, "id" | "name" | "color" | "category">;

/** Tag payload used by task view filters */
export type TaskFilterTagOption = Pick<Tag, "id" | "name" | "color">;

/** Assignee payload used by task filtering controls */
export type TaskFilterAssigneeOption = TaskPersonSummary;

/** Shared filter state for task views */
export interface TaskViewFilters {
  search: string;
  tagIds: string[];
  assigneeIds: string[];
}

/** Backwards-compatible aliases for board-specific usages */
export type BoardTagOption = TaskFilterTagOption;
export type BoardViewFilters = TaskViewFilters;

// ─── DTOs (Create / Update) ─────────────────────────────

/** Input for creating a new task */
export interface CreateTaskInput {
  projectId: string;
  title: string;
  description?: unknown;
  statusId?: string;
  priority?: Priority;
  dueDate: Date;
  startDate?: Date;
  tagIds?: string[];
  assigneeId?: string | null;
}

/** Input for updating a task */
export interface UpdateTaskInput {
  id: string;
  title?: string;
  description?: unknown;
  statusId?: string;
  priority?: Priority;
  dueDate?: Date;
  startDate?: Date;
  assigneeId?: string | null;
}

/** Input for creating a task link */
export interface CreateTaskLinkInput {
  sourceTaskId: string;
  targetTaskId: string;
  linkType: LinkType;
}

/** Input for creating a project */
export interface CreateProjectInput {
  name: string;
  slug: string;
  description?: string;
}

/** Input for updating a project */
export interface UpdateProjectInput {
  id: string;
  name?: string;
  description?: string;
  settings?: Partial<ProjectSettings>;
}

/** Input for creating/updating a workflow status */
export interface UpsertWorkflowStatusInput {
  id?: string;
  projectId: string;
  name: string;
  color: string;
  order: number;
  category: StatusCategory;
}

/** Input for creating a workflow transition */
export interface CreateWorkflowTransitionInput {
  projectId: string;
  fromStatusId: string;
  toStatusId: string;
}

/** Input for creating a tag */
export interface CreateTagInput {
  projectId: string;
  name: string;
  color?: string;
}

/** Input for creating a comment */
export interface CreateCommentInput {
  taskId: string;
  content: string;
}

// ─── Query / Filter types ────────────────────────────────

/** Filters for listing tasks */
export interface TaskFilters {
  projectId: string;
  statusIds?: string[];
  tagIds?: string[];
  priorities?: Priority[];
  dueDateFrom?: Date;
  dueDateTo?: Date;
  search?: string;
}

/** Pagination parameters */
export interface PaginationInput {
  cursor?: string;
  limit?: number;
}

/** Paginated result wrapper */
export interface PaginatedResult<T> {
  items: T[];
  nextCursor: string | null;
  totalCount: number;
}

// ─── Graph view types ────────────────────────────────────

/** A task node positioned on the graph */
/** Minimal task info needed for graph rendering */
export interface GraphTaskData {
  id: string;
  title: string;
  priority: string;
  dueDate: Date | string;
  statusId: string;
  status: { name: string; color: string; category?: string };
  tags: Array<{ tag: { id: string; name: string; color: string } }>;
  creator?: TaskPersonSummary | null;
  assignee?: TaskPersonSummary | null;
  alertAcknowledged?: boolean;
  dependencyState?: {
    blockingTaskCount: number;
    openChildCount: number;
  };
}

export interface GraphNode {
  id: string;
  task: GraphTaskData;
  x: number;
  y: number;
  width: number;
  height: number;
}

/** A dependency edge on the graph */
export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  linkType: LinkType;
  points: Array<{ x: number; y: number }>;
}

/** Result of the ELK layout computation */
export interface GraphLayout {
  nodes: GraphNode[];
  edges: GraphEdge[];
  width: number;
  height: number;
}

/** Viewport bounds for culling */
export interface Viewport {
  x: number;
  y: number;
  width: number;
  height: number;
  scale: number;
}

// ─── Search types ────────────────────────────────────────

/** Search query input */
export interface SearchInput {
  query: string;
  projectId?: string;
  filters?: {
    statusIds?: string[];
    tagIds?: string[];
    priorities?: Priority[];
    dueDateFrom?: Date;
    dueDateTo?: Date;
  };
  limit?: number;
  offset?: number;
}

/** A single search hit */
export interface SearchHit {
  task: Task;
  highlights: Record<string, string>;
}

/** Search query result */
export interface SearchResult {
  hits: SearchHit[];
  totalHits: number;
  processingTimeMs: number;
}
