import { beforeEach, describe, expect, it, vi } from "vitest";

const { createTaskWithNextNumberSpy } = vi.hoisted(() => ({
  createTaskWithNextNumberSpy: vi.fn(),
}));

vi.mock("@/server/routers/task", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@/server/routers/task")>();
  return {
    ...actual,
    createTaskWithNextNumber: ((...args: unknown[]) => {
      createTaskWithNextNumberSpy(...args);
      return (
        actual.createTaskWithNextNumber as unknown as (...callArgs: unknown[]) => Promise<unknown>
      )(...args);
    }) as typeof actual.createTaskWithNextNumber,
  };
});

import { createCallerFactory } from "@/server/trpc";
import { importExportRouter } from "@/server/routers/import-export";
import { buildExportRecord, exportHeaders, exportRecordToCells } from "@/server/services/task-transfer";
import { stringifyCsvRow } from "@/lib/csv";
import { memberOf } from "@/test/actors";
import type { PrismaMock } from "@/test/prisma-mock";

const createCaller = createCallerFactory(importExportRouter);

const PROJECT_ID = "cmab8yxxp0001a0p0r0j0e0c0t0a0a0";
const STATUS_TODO_ID = "cmab8yxxp0002s0t0a0t0u0s0t0o0d0o0";
const STATUS_DONE_ID = "cmab8yxxp0003s0t0a0t0u0s0t0d0o0n0e0";
const TAG_BACKEND_ID = "cmab8yxxp0004t0a0g0b0a0c0k0e0n0d0";
const TAG_UI_ID = "cmab8yxxp0005t0a0g0u0i0t0a0g0u0i0";
const CF_POINTS_ID = "cmab8yxxp0006c0f0p0o0i0n0t0s0f0i0";
const ASSIGNEE_ID = "cmab8yxxp0007u0s0e0r0a0s0s0i0g0n0e0";
const MANAGER_ID = "cmab8yxxp0008m0a0n0a0g0e0r0u0s0e0r0";

function callerFor(actor: ReturnType<typeof memberOf>) {
  return createCaller({
    prisma: actor.prisma as never,
    session: { user: actor.sessionUser } as never,
  });
}

function wireProjectReferenceData(prisma: PrismaMock) {
  prisma.workflowStatus.findMany.mockResolvedValue([
    {
      id: STATUS_TODO_ID,
      projectId: PROJECT_ID,
      name: "Todo",
      color: "#6b7280",
      order: 0,
      category: "todo",
      isFinal: false,
      autoArchive: false,
      autoArchiveDays: 0,
    },
    {
      id: STATUS_DONE_ID,
      projectId: PROJECT_ID,
      name: "Done",
      color: "#16a34a",
      order: 1,
      category: "done",
      isFinal: true,
      autoArchive: false,
      autoArchiveDays: 0,
    },
  ]);
  prisma.tag.findMany.mockResolvedValue([
    { id: TAG_BACKEND_ID, projectId: PROJECT_ID, name: "backend", color: "#000000", isAutoGenerated: false },
    { id: TAG_UI_ID, projectId: PROJECT_ID, name: "ui", color: "#111111", isAutoGenerated: false },
  ]);
  prisma.customField.findMany.mockResolvedValue([
    { id: CF_POINTS_ID, projectId: PROJECT_ID, name: "Story Points", type: "number", order: 0, required: false, options: null },
  ]);
}

function wireAssigneeResolution(prisma: PrismaMock) {
  const actorImplementation = prisma.user.findUnique.getMockImplementation();
  prisma.user.findMany.mockImplementation(async (args?: { where?: { email?: { in?: string[] } } }) => {
    const requested = args?.where?.email?.in ?? [];
    return requested
      .filter((email) => email.toLowerCase() === "assignee@example.com")
      .map((email) => ({ id: ASSIGNEE_ID, email }));
  });
  // canAccessProject(assignee) — assignee is a project member. The actor's own
  // wiring (installed by `memberOf`) is preserved as the fallback.
  prisma.user.findUnique.mockImplementation(async (args?: { where?: { id?: string } }) => {
    if (args?.where?.id === ASSIGNEE_ID) {
      return {
        id: ASSIGNEE_ID,
        role: "member",
        disabledAt: null,
        projectMemberships: [{ projectId: PROJECT_ID, role: "member" }],
        projectPermissionGrants: [],
        groupMemberships: [],
      };
    }
    if (actorImplementation) {
      return actorImplementation(args);
    }
    return null;
  });
}

function wireSequentialTaskNumbers(prisma: PrismaMock) {
  prisma.task.findFirst.mockImplementation(async () => ({
    taskNumber: 100 + prisma.task.create.mock.calls.length,
  }));
}

function managerActor() {
  // Manager carries task_create + workflow_manage.
  return memberOf({ userId: MANAGER_ID, projects: { [PROJECT_ID]: "manager" } });
}

function sampleCsv() {
  return [
    "Title,Status,Priority,Due Date,Assignee,Tags,cf:Story Points,Body",
    'Imported task,Done,high,2026-05-01,assignee@example.com,backend;ui,3,"Multiline\r\nbody text"',
    "Second task,Todo,low,,assignee@example.com,ui,,",
  ].join("\r\n");
}

beforeEach(() => {
  createTaskWithNextNumberSpy.mockClear();
});

describe("import preview", () => {
  it("maps aliases, previews rows, and reports would-create statuses/tags/issues", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    wireAssigneeResolution(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID });
    const caller = callerFor(actor);

    const csv = [
      "Summary,DUE DATE,Owner (email),Labels,Status,Priority,Description,cf:story points",
      "Aliased task,2026-01-15,ghost@example.com,backend;newlabel,Done,high,Body here,not-a-number",
    ].join("\r\n");

    const preview = await caller.previewCsv({ projectId: PROJECT_ID, csv });

    expect(preview.columns).toEqual([
      "Summary",
      "DUE DATE",
      "Owner (email)",
      "Labels",
      "Status",
      "Priority",
      "Description",
      "cf:story points",
    ]);
    expect(preview.mapping).toMatchObject({
      Summary: "title",
      "DUE DATE": "dueDate",
      "Owner (email)": "assigneeEmail",
      Labels: "tags",
      Status: "status",
      Priority: "priority",
      Description: "body",
      "cf:story points": "cf:Story Points",
    });
    expect(preview.rows).toHaveLength(1);
    expect(preview.rows[0].cells[0]).toBe("Aliased task");
    expect(preview.totalRows).toBe(1);
    expect(preview.wouldCreate).toEqual({
      statuses: [],
      tags: ["newlabel"],
    });
    expect(preview.issues).toEqual([
      { line: 2, message: 'Custom field "Story Points" requires a numeric value' },
      { line: 2, message: 'Assignee "ghost@example.com" was not found; the task will be left unassigned' },
    ]);
  });

  it("lists missing statuses in wouldCreate so the UI can offer to create them", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID });
    const caller = callerFor(actor);

    const preview = await caller.previewCsv({
      projectId: PROJECT_ID,
      csv: "Title,Status\r\nTask A,Brand New\r\n",
    });

    expect(preview.wouldCreate.statuses).toEqual(["Brand New"]);
    expect(preview.issues).toEqual([]);
  });

  it("rejects payloads over the 2 MB limit", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    const caller = callerFor(actor);

    await expect(
      caller.previewCsv({ projectId: PROJECT_ID, csv: `Title\r\n${"x".repeat(2 * 1024 * 1024)}` })
    ).rejects.toMatchObject({ code: "BAD_REQUEST" });
  });
});

describe("import commit", () => {
  it("round-trips a 50-task export through preview and commit", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    wireAssigneeResolution(actor.prisma);
    wireSequentialTaskNumbers(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    actor.prisma.task.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({
      id: `task-${data.taskNumber}`,
      ...data,
    }));
    const caller = callerFor(actor);

    // 1. Build a 50-task export fixture through the same code the route uses.
    const tasks = Array.from({ length: 50 }, (_, index) => ({
      taskNumber: index + 1,
      title: `Round trip task ${index + 1}`,
      body: index % 2 === 0 ? `Body with, comma and\nnewline ${index}` : null,
      priority: (["low", "medium", "high"] as const)[index % 3],
      dueDate: new Date("2026-06-01T09:00:00.000Z"),
      startDate: null,
      closedAt: index % 5 === 0 ? new Date("2026-06-02T10:00:00.000Z") : null,
      archivedAt: null,
      status: { name: index % 2 === 0 ? "Done" : "Todo" },
      project: { key: "TASK" },
      creator: { email: "creator@example.com" },
      assignee: { email: index % 3 === 0 ? "assignee@example.com" : null },
      sprint: null,
      tags: index % 2 === 0 ? [{ tag: { name: "backend" } }] : [{ tag: { name: "ui" } }],
      participants: [],
      customFieldValues:
        index % 4 === 0 ? [{ value: index, customField: { name: "Story Points" } }] : [],
    }));
    const customFields = [{ name: "Story Points" }];
    const customFieldNames = customFields.map((field) => field.name);
    const csv = [
      stringifyCsvRow(exportHeaders(customFieldNames)),
      ...tasks.map((task) =>
        stringifyCsvRow(exportRecordToCells(buildExportRecord(task, customFields), customFieldNames))
      ),
    ].join("");

    // 2. Preview the exported CSV (headers come straight from the exporter).
    const preview = await caller.previewCsv({ projectId: PROJECT_ID, csv });
    expect(preview.totalRows).toBe(50);
    expect(preview.issues).toEqual([]);
    expect(preview.wouldCreate).toEqual({ statuses: [], tags: [] });

    // 3. Commit with the proposed mapping.
    const result = await caller.commitCsv({
      projectId: PROJECT_ID,
      csv,
      mapping: preview.mapping,
      createMissing: { statuses: false, tags: false },
    });

    expect(result.createdCount).toBe(50);
    expect(result.createdStatuses).toEqual([]);
    expect(result.createdTags).toEqual([]);
    expect(createTaskWithNextNumberSpy).toHaveBeenCalledTimes(50);
    expect(actor.prisma.task.create).toHaveBeenCalledTimes(50);
    expect(actor.prisma.$transaction).toHaveBeenCalledTimes(1);

    // 4. Titles, statuses, tags, and custom fields survive the round trip.
    const createdRows = actor.prisma.task.create.mock.calls.map(
      (call) => (call[0] as { data: Record<string, unknown> }).data
    );
    expect(createdRows.map((row) => row.title)).toEqual(tasks.map((task) => task.title));

    const roundTripped = tasks.map((task, index) => {
      const row = createdRows[index];
      return {
        title: row.title,
        statusId: row.statusId,
        priority: row.priority,
        tags: (row.tags as { create: Array<{ tagId: string }> }).create.map((entry) => entry.tagId),
        customFieldValues: (
          (row.customFieldValues as { create: Array<{ customFieldId: string; value: unknown }> } | undefined)?.create ?? []
        ).map((entry) => ({ customFieldId: entry.customFieldId, value: entry.value })),
      };
    });
    for (const [index, task] of tasks.entries()) {
      const expectedStatusId = task.status.name === "Done" ? STATUS_DONE_ID : STATUS_TODO_ID;
      const expectedTagId = task.tags[0].tag.name === "backend" ? TAG_BACKEND_ID : TAG_UI_ID;
      expect(roundTripped[index].statusId).toBe(expectedStatusId);
      expect(roundTripped[index].priority).toBe(task.priority);
      expect(roundTripped[index].tags).toEqual([expectedTagId]);
      if (index % 4 === 0) {
        expect(roundTripped[index].customFieldValues).toEqual([
          { customFieldId: CF_POINTS_ID, value: index },
        ]);
      } else {
        expect(roundTripped[index].customFieldValues).toEqual([]);
      }
    }
  });

  it("MUTATION-PROVE: a malformed row aborts the whole import with line numbers and no writes", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    wireAssigneeResolution(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    const caller = callerFor(actor);

    // Row 4 has an invalid priority AND row 5 has an invalid due date.
    const csv = [
      "Title,Status,Priority,Due Date",
      "Task 1,Todo,high,2026-01-01",
      "Task 2,Todo,low,2026-01-02",
      "Task 3,Todo,catastrophic,2026-01-03",
      "Task 4,Todo,high,not-a-date",
    ].join("\r\n");

    await expect(caller.commitCsv({ projectId: PROJECT_ID, csv })).rejects.toThrow(
      /line 4: Priority "catastrophic".*line 5: Due date "not-a-date"/
    );

    // Nothing was committed: no transaction, no task/tag/status writes.
    expect(actor.prisma.$transaction).not.toHaveBeenCalled();
    expect(actor.prisma.task.create).not.toHaveBeenCalled();
    expect(actor.prisma.tag.create).not.toHaveBeenCalled();
    expect(actor.prisma.workflowStatus.create).not.toHaveBeenCalled();
    expect(actor.prisma.task.findFirst).not.toHaveBeenCalled();
    expect(createTaskWithNextNumberSpy).not.toHaveBeenCalled();
  });

  it("aborts with the line number of an unknown status when createMissing.statuses is false", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    const caller = callerFor(actor);

    const csv = "Title,Status\r\nTask 1,Todo\r\nTask 2,Marketing\r\n";
    await expect(caller.commitCsv({ projectId: PROJECT_ID, csv })).rejects.toThrow(
      /line 3: Unknown status "Marketing"/
    );
    expect(actor.prisma.$transaction).not.toHaveBeenCalled();
    expect(actor.prisma.task.create).not.toHaveBeenCalled();
  });

  it("resolves assignees by email and leaves unknown emails unassigned and reported", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    wireAssigneeResolution(actor.prisma);
    wireSequentialTaskNumbers(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    actor.prisma.task.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({
      id: `task-${data.taskNumber}`,
      ...data,
    }));
    const caller = callerFor(actor);

    const result = await caller.commitCsv({
      projectId: PROJECT_ID,
      csv: sampleCsv(),
    });

    expect(result.createdCount).toBe(2);
    expect(result.unassignedAssignees).toEqual([]);
    const rows = actor.prisma.task.create.mock.calls.map(
      (call) => (call[0] as { data: Record<string, unknown> }).data
    );
    expect(rows[0].assigneeId).toBe(ASSIGNEE_ID);
    expect(rows[1].assigneeId).toBe(ASSIGNEE_ID);

    // Multi-line body is preserved through the CSV quoting.
    expect(rows[0].body).toBe("Multiline\r\nbody text");
    // First row lands in the final status and gets closedAt.
    expect(rows[0].statusId).toBe(STATUS_DONE_ID);
    expect(rows[0].closedAt).toBeInstanceOf(Date);
    expect(rows[1].statusId).toBe(STATUS_TODO_ID);
    expect(rows[1].closedAt).toBeNull();

    const preview = await caller.previewCsv({ projectId: PROJECT_ID, csv: sampleCsv() });
    expect(preview.issues).toEqual([]);
  });

  it("reports unresolved assignees as unassigned instead of failing", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    wireSequentialTaskNumbers(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    // No resolvable users at all.
    actor.prisma.user.findMany.mockResolvedValue([]);
    actor.prisma.task.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({
      id: `task-${data.taskNumber}`,
      ...data,
    }));
    const caller = callerFor(actor);

    const result = await caller.commitCsv({
      projectId: PROJECT_ID,
      csv: "Title,Assignee\r\nTask 1,ghost@example.com\r\n",
    });

    expect(result.createdCount).toBe(1);
    expect(result.unassignedAssignees).toEqual([{ line: 2, email: "ghost@example.com" }]);
    const row = (actor.prisma.task.create.mock.calls[0][0] as { data: Record<string, unknown> }).data;
    expect(row.assigneeId).toBeNull();
  });

  it("creates missing statuses and tags only when allowed and permitted", async () => {
    const actor = managerActor();
    wireProjectReferenceData(actor.prisma);
    wireSequentialTaskNumbers(actor.prisma);
    actor.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    let createdEntities = 0;
    actor.prisma.workflowStatus.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({
      id: `new-status-${++createdEntities}`,
      projectId: PROJECT_ID,
      name: data.name,
      color: "#6b7280",
      order: data.order,
      category: "todo",
      isFinal: false,
      autoArchive: false,
      autoArchiveDays: 0,
    }));
    actor.prisma.tag.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({
      id: `new-tag-${++createdEntities}`,
      projectId: PROJECT_ID,
      name: data.name,
      color: "#6b7280",
      isAutoGenerated: false,
    }));
    actor.prisma.task.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({
      id: `task-${data.taskNumber}`,
      ...data,
    }));
    const caller = callerFor(actor);

    const result = await caller.commitCsv({
      projectId: PROJECT_ID,
      csv: "Title,Status,Tags\r\nTask 1,Marketing,backend;newtag\r\n",
      createMissing: { statuses: true, tags: true },
    });

    expect(result.createdCount).toBe(1);
    expect(result.createdStatuses).toEqual(["Marketing"]);
    expect(result.createdTags).toEqual(["newtag"]);
    expect(actor.prisma.workflowStatus.create).toHaveBeenCalledTimes(1);
    expect(actor.prisma.tag.create).toHaveBeenCalledTimes(1);

    const row = (actor.prisma.task.create.mock.calls[0][0] as { data: Record<string, unknown> }).data;
    expect(row.statusId).toBe("new-status-1");
    expect((row.tags as { create: Array<{ tagId: string }> }).create).toEqual([
      { tagId: TAG_BACKEND_ID },
      { tagId: "new-tag-2" },
    ]);
  });
});

describe("import permissions", () => {
  it("denies preview and commit for a project viewer", async () => {
    const viewer = memberOf({ userId: "viewer-user-1", projects: { [PROJECT_ID]: "viewer" } });
    wireProjectReferenceData(viewer.prisma);
    const caller = callerFor(viewer);

    await expect(caller.previewCsv({ projectId: PROJECT_ID, csv: sampleCsv() })).rejects.toMatchObject({
      code: "FORBIDDEN",
    });
    await expect(
      caller.commitCsv({ projectId: PROJECT_ID, csv: sampleCsv() })
    ).rejects.toMatchObject({ code: "FORBIDDEN" });
    expect(viewer.prisma.$transaction).not.toHaveBeenCalled();
    expect(viewer.prisma.task.create).not.toHaveBeenCalled();
  });

  it("denies creating missing statuses without workflow_manage even with task_create", async () => {
    const member = memberOf({ userId: "member-user-1", projects: { [PROJECT_ID]: "member" } });
    wireProjectReferenceData(member.prisma);
    member.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    const caller = callerFor(member);

    await expect(
      caller.commitCsv({
        projectId: PROJECT_ID,
        csv: "Title,Status\r\nTask 1,Marketing\r\n",
        createMissing: { statuses: true, tags: false },
      })
    ).rejects.toMatchObject({ code: "FORBIDDEN" });

    expect(member.prisma.$transaction).not.toHaveBeenCalled();
    expect(member.prisma.workflowStatus.create).not.toHaveBeenCalled();
    expect(member.prisma.task.create).not.toHaveBeenCalled();
  });

  it("allows a plain member to import rows that only reference existing statuses/tags", async () => {
    const member = memberOf({ userId: "member-user-2", projects: { [PROJECT_ID]: "member" } });
    wireProjectReferenceData(member.prisma);
    wireAssigneeResolution(member.prisma);
    wireSequentialTaskNumbers(member.prisma);
    member.prisma.project.findUnique.mockResolvedValue({ id: PROJECT_ID, key: "TASK" });
    member.prisma.task.create.mockImplementation(async ({ data }: { data: Record<string, unknown> }) => ({
      id: `task-${data.taskNumber}`,
      ...data,
    }));
    const caller = callerFor(member);

    const result = await caller.commitCsv({
      projectId: PROJECT_ID,
      csv: "Title,Status,Tags\r\nMember task,Todo,backend\r\n",
    });

    expect(result.createdCount).toBe(1);
    expect(member.prisma.workflowStatus.create).not.toHaveBeenCalled();
    expect(member.prisma.tag.create).not.toHaveBeenCalled();
  });
});
